-- V11: Substitui coluna 'subject' (string simples) por tabela teacher_subjects
--      permitindo que um professor tenha múltiplas disciplinas.

-- 1. Cria tabela de disciplinas do professor
CREATE TABLE teacher_subjects (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
    subject    VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_teacher_subject UNIQUE (teacher_id, subject)
);

CREATE INDEX idx_teacher_subjects_teacher ON teacher_subjects(teacher_id);

-- 2. Migra os dados existentes da coluna subject para a nova tabela
INSERT INTO teacher_subjects (teacher_id, subject)
SELECT id, subject
FROM teachers
WHERE subject IS NOT NULL AND TRIM(subject) <> '';

-- 3. Remove a coluna subject da tabela teachers
ALTER TABLE teachers DROP COLUMN subject;