-- V4: Cria tabela de turmas/séries e migra students.grade para FK

CREATE TABLE grades (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) UNIQUE NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Insere as turmas já existentes como strings únicas (evita duplicidade)
INSERT INTO grades (name)
SELECT DISTINCT grade
FROM students
WHERE grade IS NOT NULL AND grade <> '';

-- Adiciona coluna FK (nullable por enquanto para permitir a migração)
ALTER TABLE students
    ADD COLUMN grade_id BIGINT REFERENCES grades(id);

-- Preenche grade_id baseado no valor atual da coluna grade
UPDATE students s
SET grade_id = g.id
FROM grades g
WHERE g.name = s.grade;

-- Torna grade_id NOT NULL e remove coluna antiga
ALTER TABLE students
    ALTER COLUMN grade_id SET NOT NULL;

ALTER TABLE students
    DROP COLUMN grade;