-- V6: Cria tabela de cursos e vincula grades a ela, remove redundância de course em students

-- 1. Cria tabela de cursos
CREATE TABLE courses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) UNIQUE NOT NULL,
    acronym    VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 2. Migra os cursos existentes de grades para courses (valores únicos)
INSERT INTO courses (name, acronym)
SELECT DISTINCT course, UPPER(LEFT(REGEXP_REPLACE(course, '[^A-Za-z ]', '', 'g'), 10))
FROM grades
WHERE course IS NOT NULL AND course <> '' AND course <> 'Não informado';

-- Insere um curso padrão para grades sem curso definido
INSERT INTO courses (name, acronym)
SELECT 'Não informado', 'N/A'
WHERE NOT EXISTS (SELECT 1 FROM courses WHERE name = 'Não informado');

-- 3. Adiciona coluna course_id em grades
ALTER TABLE grades
    ADD COLUMN course_id BIGINT REFERENCES courses(id);

-- 4. Preenche course_id com base no campo course atual
UPDATE grades g
SET course_id = c.id
FROM courses c
WHERE c.name = g.course;

-- Para grades sem correspondência, usa o curso padrão
UPDATE grades g
SET course_id = (SELECT id FROM courses WHERE name = 'Não informado')
WHERE g.course_id IS NULL;

-- 5. Torna course_id NOT NULL e remove coluna antiga de grades
ALTER TABLE grades
    ALTER COLUMN course_id SET NOT NULL;

ALTER TABLE grades
    DROP COLUMN course;

-- 6. Remove coluna course de students (agora derivada via grade -> course)
ALTER TABLE students
    DROP COLUMN IF EXISTS course;