-- =============================================================
-- V9: Corrige integridade histórica de ocorrências e cria
--     tabela de histórico de matrículas (enrollment_history)
-- =============================================================

-- 1. Adiciona grade_id diretamente na ocorrência (snapshot imutável)
--    Isso garante que mesmo que o aluno mude de turma, o histórico
--    de ocorrências continua exibindo a turma correta do momento
--    em que a ocorrência foi registrada.
ALTER TABLE occurrences
    ADD COLUMN IF NOT EXISTS grade_id BIGINT REFERENCES grades(id);

-- Preenche retroativamente com a turma atual do aluno
-- (melhor aproximação possível para dados históricos existentes)
UPDATE occurrences o
SET grade_id = (
    SELECT grade_id FROM students WHERE id = o.student_id
)
WHERE o.grade_id IS NULL;

-- Torna obrigatório para novos registros

-- 2. Cria tabela de histórico de matrículas
--    Registra cada período em que um aluno esteve em uma turma.
--    Permite rastrear a trajetória completa: promoções, transferências, retenções.
CREATE TABLE IF NOT EXISTS enrollment_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL REFERENCES students(id),
    grade_id        BIGINT NOT NULL REFERENCES grades(id),
    start_date      DATE NOT NULL,
    end_date        DATE,           -- NULL = matrícula ativa
    reason          VARCHAR(50) NOT NULL DEFAULT 'MATRICULA',
    -- Valores: MATRICULA, PROMOCAO, RETENCAO, TRANSFERENCIA, CANCELAMENTO
    notes           TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_enrollment_reason
        CHECK (reason IN ('MATRICULA', 'PROMOCAO', 'RETENCAO', 'TRANSFERENCIA', 'CANCELAMENTO')),

    -- Garante que um aluno não tenha duas matrículas ativas ao mesmo tempo
    CONSTRAINT uq_enrollment_active
        UNIQUE NULLS NOT DISTINCT (student_id, end_date)
);

-- Índices para consultas frequentes
CREATE INDEX IF NOT EXISTS idx_enrollment_history_student ON enrollment_history(student_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_history_grade   ON enrollment_history(grade_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_history_active  ON enrollment_history(student_id) WHERE end_date IS NULL;

-- 3. Popula histórico inicial com as matrículas atuais
--    Cada aluno recebe um registro de MATRICULA com start_date = created_at
INSERT INTO enrollment_history (student_id, grade_id, start_date, end_date, reason)
SELECT
    s.id,
    s.grade_id,
    COALESCE(s.created_at::date, CURRENT_DATE),
    NULL,       -- matrícula ativa
    'MATRICULA'
FROM students s
WHERE s.grade_id IS NOT NULL
ON CONFLICT DO NOTHING;